src/models/Item.php
<?php

namespace quoma\modules\config\models;

use quoma\media\behaviors\MediaBehavior;
use quoma\media\models\ModelHasMedia;
use Yii;
use quoma\modules\config\ConfigModule;
use yii\web\Application;

/**
 * This is the model class for table "item".
 *
 * @property integer $item_id
 * @property string $attr
 * @property string $type
 * @property string $default
 * @property string $label
 * @property string $description
 * @property integer $multiple
 * @property integer $category_category_id
 *
 * @property Config[] $configs
 * @property Category $categoryCategory
 */
class Item extends \quoma\core\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_config');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        if (Yii::$app instanceof Application) {

            return [
                'media' => [
                    'class' => MediaBehavior::class,
                    'modelClass' => static::class,
                ],
            ];
        } else {
            return [];
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['attr', 'category_id'], 'required'],
            [['multiple', 'category_id'], 'integer'],
            [['label'], 'string', 'max' => 140],
            [['attr', 'type'], 'string', 'max' => 45],
            [['default', 'description', 'model', 'model_name_attr'], 'string', 'max' => 255],
            [['attr'], 'unique'],
            [['superadmin'], 'boolean'],
            [['model', 'model_name_attr'], 'required', 'when' => function($model) {
                return $model->type == 'dropdownModel';
            }],
            [['model'], function(){
                if(!class_exists($this->model)){
                    $this->addError('model', Yii::t('app', 'Class {model} does not exists.', ['model' => $this->model]));
                }
            }, 'when' => function($model) {
                return $model->type == 'dropdownModel';
            }],
            [['model_name_attr'], function(){
                if(empty($this->model) || !class_exists($this->model)){
                    return;
                }
                $aux = new $this->model;
                if(!$aux->hasProperty($this->model_name_attr) && !$aux->hasAttribute($this->model_name_attr)){
                    $this->addError('model_name_attr', Yii::t('app', 'Attribute {name} is not defined.', ['name' => $this->model_name_attr]));
                }
            }, 'when' => function($model) {
                return $model->type == 'dropdownModel';
            }]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'item_id' => ConfigModule::t('Item ID'),
            'attr' => ConfigModule::t('Attr'),
            'type' => ConfigModule::t('Type'),
            'default' => ConfigModule::t('Default'),
            'label' => ConfigModule::t('Label'),
            'description' => ConfigModule::t('Description'),
            'multiple' => ConfigModule::t('Multiple'),
            'category_id' => ConfigModule::t('Category'),
            'superadmin' => ConfigModule::t('Superadmin only'),
            'model' => ConfigModule::t('Model Class'),
            'model_name_attr' => ConfigModule::t('Model name attribute'),
        ];
    }    


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConfigs()
    {
        return $this->hasMany(Config::className(), ['item_id' => 'item_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRules()
    {
        return $this->hasMany(Rule::className(), ['item_id' => 'item_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['category_id' => 'category_id']);
    }
             
    /**
     * @inheritdoc
     * Strong relations: None.
     */
    public function getDeletable()
    {
        return true;
    }
    
    /**
     * @brief Deletes weak relations for this model on delete
     * Weak relations: Configs, CategoryCategory.
     */
    protected function unlinkWeakRelations(){
        
        $this->unlinkAll('configs', true);
        $this->unlinkAll('rules', true);
        
    }
    
    /**
     * @inheritdoc
     */
    public function beforeDelete()
    {
        if (parent::beforeDelete()) {
            if($this->getDeletable()){
                $this->unlinkWeakRelations();
                return true;
            }
        } else {
            return false;
        }
    }
    
    public static function types()
    {
        return [
            'textInput' => Yii::t('app', 'Text'),
            'textarea' =>  Yii::t('app', 'Textarea'),
            'checkbox' => Yii::t('app','Checkbox'),
            'passwordInput' => Yii::t('app','Password'),
            'dropdownModel' => Yii::t('app','Dropdown Model'),
            'image' => Yii::t('app','Image'),
            'images' => Yii::t('app','Images'),
            'media' => Yii::t('app','Media'),
        ];
    }
    
    public static function getItems($category)
    {
        
        $query = Item::find();
        
        $query->where(['category_id' => $category->category_id]);
        
        if(!Yii::$app->user->isSuperadmin){
            $query->andWhere(['superadmin' => 0]);
        }
        
        return $query->all();
        
    }
    
    /**
     * Para tipo dropdownModel, busca los modelos
     * @return type
     */
    public function getModelDropdownItems()
    {
        $aux = new $this->model;
        
        $items = $aux::find()->all();
        
        $nameAttr = $this->model_name_attr;
        return \yii\helpers\ArrayHelper::map($items, $aux->primaryKey(), $nameAttr);
    }

    /**
     * @param $attr
     * @param $value
     * @param bool $validate
     * @return array|Config|\yii\db\ActiveRecord|null
     * @throws \yii\web\HttpException
     */
    public static function setValue($attr, $value, $validate = true) {

        $item = Item::find()->where(['attr' => $attr])->one();
        if($item === null){
            throw new \Exception('Configuration item not found: '.$attr);
        }

        if (!\Yii::$app->request->isConsoleRequest && $item->superadmin && !Yii::$app->user->isSuperadmin) {
            throw new \yii\web\HttpException(403, ConfigModule::t('Forbidden.'));
        }

        if($item->isMediaType){
            $item->saveMedia($value);
            return $item;
        }

        $config = Config::find()->where(['item_id' => $item->item_id])->one();

        if (empty($config)) {
            $config = new Config;
            $config->item_id = $item->item_id;
        }

        $config->value = $value;

        $config->save($validate);

        return $config;
    }

    /**
     * Setea los recursos multimedia al modelo
     * @param array $media
     * @throws \yii\web\HttpException
     */
    public function saveMedia($values){

        $key = $this->primaryKey;
        $class = static::class;

        //Quitamos las relaciones actuales
        ModelHasMedia::deleteAll(['model_id'=>$key, 'model'=>$class]);

        //Guardamos las nuevas relaciones
        foreach ($values as $order=>$m){
            $mhm = new ModelHasMedia();

            $mhm->media_id = $m;
            $mhm->model_id = $key;
            $mhm->model = $class;
            $mhm->order = $order;

            $mhm->save();
        }
    }

    public function getIsMediaType()
    {
        return in_array($this->type, ['media', 'image', 'images']);
    }

}

src/controllers/ItemController.php
<?php

namespace quoma\modules\config\controllers;

use Yii;
use quoma\modules\config\models\Item;
use quoma\modules\config\models\search\ItemSearch;
use quoma\core\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ItemController implements the CRUD actions for Item model.
 */
class ItemController extends Controller
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),[
        ]);
    }

    /**
     * Lists all Item models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Item model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Item model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Item();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->item_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Item model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->item_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Item model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Item model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Item the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Item::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/controllers/RuleController.php
<?php

namespace quoma\modules\config\controllers;

use Yii;
use quoma\modules\config\models\Rule;
use quoma\modules\config\models\search\RuleSearch;
use quoma\core\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RuleController implements the CRUD actions for Rule model.
 */
class RuleController extends Controller
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),[
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'load-attributes' => ['post'],
                ],
            ],
        ]);
    }

    /**
     * Lists all Rule models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RuleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rule model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Rule model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($item)
    {
        $model = new Rule();
        Rule::getValidatorAttributes('integer');
        
        $item = \quoma\modules\config\models\Item::findOne($item);
        if($item === null){
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        
        $model->item_id = $item->item_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['item/view', 'id' => $model->item_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'item' => $item
            ]);
        }
    }
    
    public function actionLoadAttributes()
    {
        
        $validator = Yii::$app->request->post('validator');
        
        $attrs = Rule::getValidatorAttributes($validator);
        
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        
        return [
            'attributes' => $attrs,
            'status' => 'success'
        ];
        
    }

    /**
     * Updates an existing Rule model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['item/view', 'id' => $model->item_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Rule model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect( Yii::$app->request->referrer );
    }

    /**
     * Finds the Rule model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Rule the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rule::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/views/item/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use quoma\modules\config\ConfigModule;

/* @var $this yii\web\View */
/* @var $model quoma\modules\config\models\Item */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?= $form->field($model, 'category_id')->dropDownList(yii\helpers\ArrayHelper::map(
        \quoma\modules\config\models\Category::find()->all(), 'category_id', 'name'
    )) ?>

    <?= $form->field($model, 'attr')->textInput(['maxlength' => 45]) ?>
    
    <?= $form->field($model, 'label')->textInput(['maxlength' => 45]) ?>

    <?= $form->field($model, 'type')->dropDownList(quoma\modules\config\models\Item::types(), ['data-type' => true]) ?>
    
    <div data-show-on-type="dropdownModel" style="<?php if($model->type !== 'dropdownModel') echo 'display:none'; ?>">
        <?= $form->field($model, 'model', ['enableClientValidation' => false])->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'model_name_attr', ['enableClientValidation' => false])->textInput(['maxlength' => true]) ?>
    </div>

    <?= $form->field($model, 'default')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => 255]) ?>
    
    <?= $form->field($model, 'superadmin')->checkbox() ?>

    <?= $form->field($model, 'multiple')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? ConfigModule::t('Create') : ConfigModule::t('Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    var Item = new function()
    {
        this.init = function()
        {
            $('[data-type]').on('change', function(){
                var type = $(this).val();
                $('[data-show-on-type]').not('[data-show-on-type="'+type+'"]').hide();
                $('[data-show-on-type="'+type+'"]').show();
            });
            
        }
        
    }
</script>
<?php $this->registerJs('Item.init();') ?>

src/views/item/create.php
<?php

use yii\helpers\Html;
use quoma\modules\config\ConfigModule;

/* @var $this yii\web\View */
/* @var $model quoma\modules\config\models\Item */

$this->title = ConfigModule::t('Create {modelClass}', ['modelClass' => ConfigModule::t('Item')]);
$this->params['breadcrumbs'][] = ['label' => ConfigModule::t('Config Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-create">

    <div class="row">
    	<div class="col-sm-8 col-sm-offset-2">
		    <h1><?= Html::encode($this->title) ?></h1>

		    <?= $this->render('_form', [
		        'model' => $model,
		    ]) ?>
    	</div>
    </div>

</div>

src/views/item/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use quoma\modules\config\ConfigModule;

/* @var $this yii\web\View */
/* @var $searchModel quoma\modules\config\models\search\ItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = ConfigModule::t('Config Items');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-index">

   <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?= Html::a("<span class='glyphicon glyphicon-plus'></span> " . ConfigModule::t('Create {modelClass}', [
        'modelClass' => ConfigModule::t('Item'),
    ]), 
            ['create'], 
            ['class' => 'btn btn-success']) 
            ;?>
        </p>
   </div>
    

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'options' => ['class' => 'table-responsive'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'item_id',
            'attr',
            'type',
            'default',
            'label',
            // 'description',
            // 'multiple',
            // 'category_id',

            [
                'class' => 'quoma\core\grid\ActionColumn',
            ],
        ],
    ]); ?>

</div>

src/views/item/update.php
<?php

use yii\helpers\Html;
use quoma\modules\config\ConfigModule;

/* @var $this yii\web\View */
/* @var $model quoma\modules\config\models\Item */

$this->title = ConfigModule::t('Update {modelClass}: ', [
    'modelClass' => 'Item',
]) . ' ' . $model->attr;
$this->params['breadcrumbs'][] = ['label' => ConfigModule::t('Config Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->attr, 'url' => ['view', 'id' => $model->item_id]];
$this->params['breadcrumbs'][] = ConfigModule::t('Update');
?>
<div class="item-update">

    <div class="row">
    	<div class="col-sm-8 col-sm-offset-2">
		    <h1><?= Html::encode($this->title) ?></h1>

		    <?= $this->render('_form', [
		        'model' => $model,
		    ]) ?>
    	</div>
    </div>

</div>

src/views/item/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use quoma\modules\config\ConfigModule;

/* @var $this yii\web\View */
/* @var $model quoma\modules\config\models\Item */

$this->title = $model->attr;
$this->params['breadcrumbs'][] = ['label' => ConfigModule::t('Config Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-view">

    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . ConfigModule::t('Update'), ['update', 'id' => $model->item_id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . ConfigModule::t('Add Validator'), ['rule/create', 'item' => $model->item_id], ['class' => 'btn btn-success']) ?>
            <?php if($model->deletable) echo Html::a('<span class="glyphicon glyphicon-remove"></span> ' . ConfigModule::t('Delete'), ['delete', 'id' => $model->item_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => ConfigModule::t('Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    </div>
    
    <?php
    $validators = '';
    foreach ($model->rules as $i => $rule){
        $validators .= Html::a($rule->validator, ['rule/view', 'id' => $rule->rule_id]);
        if($i < count($model->rules) - 1 ){
            $validators .= ', ';
        }
    }
    ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'item_id',
            'attr',
            'type',
            'default',
            'label',
            'description',
            [
                'attribute' => 'category_id',
                'value' => $model->category->name
            ],
            'superadmin:boolean',
            'multiple:boolean',
            [
                'label' => ConfigModule::t('Validators'),
                'value' => $validators,
                'format' => 'html'
            ]
        ],
    ]) ?>
    
    <h2><?= ConfigModule::t('Validators') ?></h2>
    <?php 
    $dataProvider = new yii\data\ActiveDataProvider([
        'query' => $model->getRules()
    ]);
    ?>
    
    <?= yii\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => false,
        'options' => ['class' => 'table-responsive'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'rule_id',
            'validator',
            'message',

            [
                'class' => 'quoma\core\grid\ActionColumn',
                'controller' => 'rule',
            ],
        ],
    ]); ?>
    

</div>